# Generated by Django 2.0.7 on 2018-08-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created',
        ),
        migrations.AddField(
            model_name='note',
            name='number_of_unique',
            field=models.IntegerField(default=0),
        ),
    ]
