# Generated by Django 2.0.7 on 2018-08-01 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20180802_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
    ]
