# Generated by Django 2.0.7 on 2018-08-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Note'},
        ),
        migrations.RemoveField(
            model_name='note',
            name='created',
        ),
        migrations.AddField(
            model_name='note',
            name='number_of_unique',
            field=models.IntegerField(default=0, verbose_name='Number of unique words'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, max_length=8000, null=True, verbose_name='Note text'),
        ),
    ]
